//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string Phone { get; set; }
        public string Landmark { get; set; }
        public string Address { get; set; }
        public string Town_City { get; set; }
        public string Addresstype { get; set; }
        public int Product_fid { get; set; }
        public int quantity { get; set; }
        public string FullName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
